name: Documentation

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]

    steps:
    - uses: actions/checkout@v3

    - name: Cache emodb
      uses: actions/cache@v3
      with:
        path: ~/audb
        key: emodb-1.4.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Ubuntu - install libsndfile
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends --yes libsndfile1

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      # DOCS
    - name: Ubuntu - install graphviz
      run: sudo apt-get install --yes graphviz

    - name: Install docs requirements
      run: pip install -r docs/requirements.txt

    - name: Test building documentation
      run: python -m sphinx docs/ docs/_build/ -b html -W

    - name: Check links in documentation
      run: python -m sphinx docs/ docs/_build/ -b linkcheck -W
