name: Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]
        pandas: [ 'pandas==2.1.0', 'pandas==2.2.0']

    steps:
    - uses: actions/checkout@v4

    - name: Cache emodb
      uses: actions/cache@v4
      with:
        path: ~/audb
        key: emodb-1.4.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Ubuntu - install libsndfile
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends --yes libsndfile1

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "${{ matrix.pandas }}"

    # TESTS
    - name: Ubuntu - install ffmpeg/mediainfo
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends --yes ffmpeg mediainfo

    - name: Install tests requirements
      run: pip install -r tests/requirements.txt

    - name: Test with pytest
      run: python -m pytest
